[package]
name = "fastcopy"
version = "1.0.2"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
crossbeam-channel = "0.5.16"
eframe = { version = "0.36.1", default-features = false, features = ["glow"] }
fs2 = "0.4.3"
rfd = { version = "0.17.2", default-features = false }
winrt-notification = "0.5.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
trash = { version = "5.2.6", default-features = false, features = ["coinit_apartmentthreaded"] }
walkdir = "2.5.0"
ignore = "0.4"
regex = "1.12.2"
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_Graphics_Gdi", "Win32_Security", "Win32_Storage_FileSystem", "Win32_UI_HiDpi", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging", "Win32_System_DataExchange", "Win32_System_IO", "Win32_System_Ioctl", "Win32_System_Memory", "Win32_System_Registry", "Win32_System_Threading"] }
winreg = "0.56.0"
windows = { version = "0.56", features = ["Win32_Foundation", "Win32_Storage_FileSystem", "Win32_System_Com", "Win32_System_Ole", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }

[dev-dependencies]
tempfile = "3.27.0"

[build-dependencies]
winres = "0.1.12"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
opt-level = "s"
